import type { ProjectWithRelations, Category } from '@/types';
import { CATEGORIES } from './constants';

// ============================================================
// Mock 数据 — 用于数据库未连接时的首页展示
// 让 MVP 在 0 项目时也能展示网站轮廓
// ============================================================

const mockCategories: Category[] = CATEGORIES.map((cat, i) => ({
  ...cat,
  id: `cat-mock-${i}`,
  created_at: '2026-01-01T00:00:00Z',
})) as Category[];

const mockProjects: ProjectWithRelations[] = [
  {
    id: 'mock-1',
    title: 'HabitForge',
    slug: 'habitforge',
    tagline: 'AI-powered habit tracker that learns your patterns and adapts reminders',
    description: 'HabitForge uses AI to build a smart habit tracking system that analyzes your behavior patterns.',
    url: 'https://example.com/habitforge',
    github_url: 'https://github.com/example/habitforge',
    screenshot_url: 'https://placehold.co/1200x750/FFF7ED/F97316?text=HabitForge',
    category_id: mockCategories[1].id,
    author_id: 'mock-author-1',
    status: 'featured',
    dev_duration: '3 weeks',
    is_profitable: true,
    view_count: 1240,
    created_at: '2026-06-07T00:00:00Z',
    updated_at: '2026-06-07T00:00:00Z',
    published_at: '2026-06-07T00:00:00Z',
    category: mockCategories[1],
    author: { id: 'mock-author-1', name: 'Sarah Chen', email: null, avatar_url: null, website: null, twitter: '@sarahchen', github: 'sarahchen', created_at: '' },
    ai_tools: [
      { id: 'tool-1', name: 'Claude Code', slug: 'claude-code', website: 'https://claude.ai', created_at: '' },
    ],
    tech_stack: ['Next.js', 'Supabase', 'Tailwind CSS'],
  },
  {
    id: 'mock-2',
    title: 'DevRelay',
    slug: 'devrelay',
    tagline: 'Real-time developer collaboration tool with AI code review',
    description: 'DevRelay connects developers in real-time with AI-powered code review.',
    url: 'https://example.com/devrelay',
    github_url: 'https://github.com/example/devrelay',
    screenshot_url: 'https://placehold.co/1200x750/EEF2FF/4F46E5?text=DevRelay',
    category_id: mockCategories[7].id,
    author_id: 'mock-author-2',
    status: 'featured',
    dev_duration: '2 months',
    is_profitable: false,
    view_count: 890,
    created_at: '2026-06-09T00:00:00Z',
    updated_at: '2026-06-09T00:00:00Z',
    published_at: '2026-06-09T00:00:00Z',
    category: mockCategories[7],
    author: { id: 'mock-author-2', name: 'Marcus Rivera', email: null, avatar_url: null, website: null, twitter: '@marcusdev', github: 'marcusrivera', created_at: '' },
    ai_tools: [
      { id: 'tool-1', name: 'Claude Code', slug: 'claude-code', website: 'https://claude.ai', created_at: '' },
      { id: 'tool-2', name: 'Cursor', slug: 'cursor', website: 'https://cursor.sh', created_at: '' },
    ],
    tech_stack: ['React', 'Node.js', 'PostgreSQL', 'WebSocket'],
  },
  {
    id: 'mock-3',
    title: 'FinSight',
    slug: 'finsight',
    tagline: 'Personal finance dashboard with AI spending predictions',
    description: 'A beautiful personal finance dashboard that uses AI to predict your spending patterns.',
    url: 'https://example.com/finsight',
    github_url: null,
    screenshot_url: 'https://placehold.co/1200x750/ECFDF5/10B981?text=FinSight',
    category_id: mockCategories[2].id,
    author_id: 'mock-author-3',
    status: 'featured',
    dev_duration: '1 month',
    is_profitable: true,
    view_count: 2100,
    created_at: '2026-05-31T00:00:00Z',
    updated_at: '2026-05-31T00:00:00Z',
    published_at: '2026-05-31T00:00:00Z',
    category: mockCategories[2],
    author: { id: 'mock-author-3', name: 'Alex Kim', email: null, avatar_url: null, website: null, twitter: '@alexkim', github: 'alexkim', created_at: '' },
    ai_tools: [
      { id: 'tool-3', name: 'Bolt', slug: 'bolt', website: 'https://bolt.new', created_at: '' },
      { id: 'tool-4', name: 'Windsurf', slug: 'windsurf', website: 'https://codeium.com/windsurf', created_at: '' },
    ],
    tech_stack: ['Vue.js', 'Python', 'FastAPI'],
  },
  {
    id: 'mock-4',
    title: 'LingoSpark',
    slug: 'lingospark',
    tagline: 'Learn languages through AI-generated interactive stories',
    description: 'LingoSpark creates personalized language learning experiences through AI-generated stories.',
    url: 'https://example.com/lingospark',
    github_url: 'https://github.com/example/lingospark',
    screenshot_url: 'https://placehold.co/1200x750/FEF3C7/F59E0B?text=LingoSpark',
    category_id: mockCategories[3].id,
    author_id: 'mock-author-4',
    status: 'approved',
    dev_duration: '2 days',
    is_profitable: false,
    view_count: 340,
    created_at: '2026-06-11T00:00:00Z',
    updated_at: '2026-06-11T00:00:00Z',
    published_at: '2026-06-11T00:00:00Z',
    category: mockCategories[3],
    author: { id: 'mock-author-4', name: 'Priya Sharma', email: null, avatar_url: null, website: null, twitter: '@priyacodes', github: 'priyasharma', created_at: '' },
    ai_tools: [
      { id: 'tool-5', name: 'Lovable', slug: 'lovable', website: 'https://lovable.dev', created_at: '' },
    ],
    tech_stack: ['Svelte', 'OpenAI'],
  },
  {
    id: 'mock-5',
    title: 'PixelQuest',
    slug: 'pixelquest',
    tagline: 'AI-generated pixel art RPG with infinite quests',
    description: 'An RPG where every quest, character, and dialogue is generated by AI.',
    url: 'https://example.com/pixelquest',
    github_url: 'https://github.com/example/pixelquest',
    screenshot_url: 'https://placehold.co/1200x750/FCE7F3/EC4899?text=PixelQuest',
    category_id: mockCategories[5].id,
    author_id: 'mock-author-5',
    status: 'approved',
    dev_duration: '3 months',
    is_profitable: false,
    view_count: 560,
    created_at: '2026-06-04T00:00:00Z',
    updated_at: '2026-06-04T00:00:00Z',
    published_at: '2026-06-04T00:00:00Z',
    category: mockCategories[5],
    author: { id: 'mock-author-5', name: 'Tom Baker', email: null, avatar_url: null, website: null, twitter: '@tombaker', github: 'tombaker', created_at: '' },
    ai_tools: [
      { id: 'tool-1', name: 'Claude Code', slug: 'claude-code', website: 'https://claude.ai', created_at: '' },
      { id: 'tool-2', name: 'Cursor', slug: 'cursor', website: 'https://cursor.sh', created_at: '' },
    ],
    tech_stack: ['Phaser.js', 'Node.js'],
  },
  {
    id: 'mock-6',
    title: 'MailMuse',
    slug: 'mailmuse',
    tagline: 'AI email assistant that drafts replies in your voice',
    description: 'MailMuse analyzes your email writing style and drafts replies that sound exactly like you.',
    url: 'https://example.com/mailmuse',
    github_url: null,
    screenshot_url: 'https://placehold.co/1200x750/EEF2FF/6366F1?text=MailMuse',
    category_id: mockCategories[4].id,
    author_id: 'mock-author-6',
    status: 'approved',
    dev_duration: '2 days',
    is_profitable: true,
    view_count: 780,
    created_at: '2026-06-12T00:00:00Z',
    updated_at: '2026-06-12T00:00:00Z',
    published_at: '2026-06-12T00:00:00Z',
    category: mockCategories[4],
    author: { id: 'mock-author-6', name: 'Lena Müller', email: null, avatar_url: null, website: null, twitter: '@lenacodes', github: 'lenamueller', created_at: '' },
    ai_tools: [
      { id: 'tool-1', name: 'Claude Code', slug: 'claude-code', website: 'https://claude.ai', created_at: '' },
      { id: 'tool-6', name: 'v0', slug: 'v0', website: 'https://v0.dev', created_at: '' },
    ],
    tech_stack: ['Next.js', 'Gmail API', 'OpenAI'],
  },
  {
    id: 'mock-7',
    title: 'SaaSBoilerplate',
    slug: 'saasboilerplate',
    tagline: 'Next.js SaaS starter with auth, payments, and AI integration',
    description: 'A production-ready SaaS boilerplate. Built to help solo developers ship faster.',
    url: 'https://example.com/saasboilerplate',
    github_url: 'https://github.com/example/saasboilerplate',
    screenshot_url: 'https://placehold.co/1200x750/F8FAFC/0F172A?text=SaaSBoilerplate',
    category_id: mockCategories[0].id,
    author_id: 'mock-author-1',
    status: 'approved',
    dev_duration: '1 month',
    is_profitable: true,
    view_count: 3200,
    created_at: '2026-05-25T00:00:00Z',
    updated_at: '2026-05-25T00:00:00Z',
    published_at: '2026-05-25T00:00:00Z',
    category: mockCategories[0],
    author: { id: 'mock-author-1', name: 'Sarah Chen', email: null, avatar_url: null, website: null, twitter: '@sarahchen', github: 'sarahchen', created_at: '' },
    ai_tools: [
      { id: 'tool-2', name: 'Cursor', slug: 'cursor', website: 'https://cursor.sh', created_at: '' },
    ],
    tech_stack: ['Next.js', 'Supabase', 'Stripe'],
  },
  {
    id: 'mock-8',
    title: 'WeatherVane',
    slug: 'weathervane',
    tagline: 'Hyper-local weather app with AI-powered activity recommendations',
    description: 'WeatherVane combines weather data with AI to recommend outdoor activities.',
    url: 'https://example.com/weathervane',
    github_url: null,
    screenshot_url: 'https://placehold.co/1200x750/E0F2FE/0284C7?text=WeatherVane',
    category_id: mockCategories[6].id,
    author_id: 'mock-author-5',
    status: 'approved',
    dev_duration: '1 week',
    is_profitable: false,
    view_count: 150,
    created_at: '2026-06-13T00:00:00Z',
    updated_at: '2026-06-13T00:00:00Z',
    published_at: '2026-06-13T00:00:00Z',
    category: mockCategories[6],
    author: { id: 'mock-author-5', name: 'Tom Baker', email: null, avatar_url: null, website: null, twitter: '@tombaker', github: 'tombaker', created_at: '' },
    ai_tools: [
      { id: 'tool-4', name: 'Windsurf', slug: 'windsurf', website: 'https://codeium.com/windsurf', created_at: '' },
    ],
    tech_stack: ['React Native', 'Expo'],
  },
];

export function getMockHomePageData() {
  return {
    featured: mockProjects.filter(p => p.status === 'featured'),
    latest: [...mockProjects].sort((a, b) =>
      new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
    ),
    popular: [...mockProjects].sort((a, b) => b.view_count - a.view_count),
    categories: mockCategories,
    stats: {
      total_projects: mockProjects.length,
      total_builders: new Set(mockProjects.map(p => p.author_id)).size,
      total_categories: mockCategories.length,
    },
  };
}

export function getMockProjects(): ProjectWithRelations[] {
  return mockProjects;
}

export function getMockCategories(): Category[] {
  return mockCategories;
}
